@startuml
class Account {
  + id: string
  - account_name: string
  - tag: string
  - balance: number
  - available_balance: number
  - transactions: Transaction[]
  - created_at: date
  - updated_at: date
  + setData(account_name: string, tag: string, balance: number, available_balance: number): void
  + setBalance(balance: number): void
  + setAvailableBalance(balance: number): void
  + getBalance(): number
  + getAvailableBalance(): number
}

class Transaction {
  + id: string
  - account: Account
  - order_id: string
  - order_code: string
  - transaction_type: string
  - debit: string
  - credit: number
  - balance: number
  + getCredit(): number
  + getBalance(): date
}

Account "1" <--> "0..*" Transaction: Transactions


@enduml